drop table ATGTR_CAT_SHOW;
drop table ATGTR_PRIZE;
drop table ATGTR_SHOW;
drop table ATGTR_PEDIGREE;
drop table ATGTR_VACCINATION;
drop table ATGTR_PERSIAN_CAT;
drop table ATGTR_MAINE_COON_CAT;
drop table ATGTR_CAT;
drop table ATGTR_OWNER;
drop table ATGTR_FELINE;


create table ATGTR_OWNER(
		OWNER_ID VARCHAR2(40) NOT NULL,
		OWNER_NAME VARCHAR2(254),
		FELINE_ID VARCHAR2(40),
		constraint ATGTR_OWNER_PK primary key(OWNER_ID)
	);

create index ATGTR_OWNER_IDX
	on ATGTR_OWNER (OWNER_NAME);


create table ATGTR_FELINE(
		FELINE_ID VARCHAR2(40) NOT NULL,
		FELINE_NAME VARCHAR2(254),
		constraint ATGTR_FELINE_PK primary key(FELINE_ID)
		);
	
	
create index ATGTR_FELINE_IDX
    on ATGTR_FELINE (FELINE_NAME);
	

create table ATGTR_CAT(
		CAT_ID VARCHAR2(40) NOT NULL,
		CAT_NAME VARCHAR2(254),
		CAT_BREED NUMBER,
		constraint ATGTR_CAT_PK primary key(CAT_ID)
		);

create index ATGTR_CAT_IDX
	on 	ATGTR_CAT (CAT_NAME);
	

create table ATGTR_FELINE_CAT(
		FELINE_ID VARCHAR2(40) NOT NULL,
		CAT_ID VARCHAR2(40) NOT NULL,
		constraint ATGTR_FELINE_CAT_PK primary key(FELINE_ID, CAT_ID)
	);

	
create table ATGTR_PERSIAN_CAT(
		CAT_ID VARCHAR2(40) NOT NULL,
		LENGHT_HAIR NUMBER(4, 2),
		constraint ATGTR_PERSIAN_CAT_PK primary key(CAT_ID)
		);
	
	
create table ATGTR_MAINE_COON_CAT(
		CAT_ID VARCHAR2(40) NOT NULL,
		LENGHT_BODY NUMBER(4, 2),
		constraint ATGTR_MAINE_COON_CAT_PK primary key(CAT_ID)
		);
		
create table ATGTR_PEDIGREE(
		CAT_ID VARCHAR2(40) NOT NULL,
		PEDIGREE_NUMBER VARCHAR2(254),
		constraint ATGTR_PEDIGREE_PK primary key(CAT_ID)
	);

	
create table ATGTR_VACCINATION(
		VACCINATION_ID VARCHAR2(40) NOT NULL,
		VACCINATION_NUMBER VARCHAR2(254),
		VACCINATION_DATE DATE,
		constraint ATGTR_VACCINATION_PK primary key (VACCINATION_ID)
	);
	
create table ATGTR_CAT_VACCINATION(
		CAT_ID VARCHAR2(40) NOT NULL,
		VACCINATION_KEY VARCHAR2(254) NOT NULL,
		VACCINATION_ID_VALUE VARCHAR2(40),
		constraint ATGTR_CAT_VACCINATION_PK primary key (CAT_ID, VACCINATION_KEY)
	);
	

create table ATGTR_PRIZE(
		PRIZE_ID VARCHAR2(40) NOT NULL,
		PLACE NUMBER(10, 0),
		AWARD VARCHAR2(254),
		constraint ATGTR_PRIZE_PK primary key (PRIZE_ID)
	);
	
	
create index ATGTR_PRIZE_IDX 
	on ATGTR_PRIZE (PLACE);
	
create table ATGTR_SHOW(
		SHOW_ID VARCHAR2(40) NOT NULL,
		SHOW_NAME VARCHAR2(254),
		SHOW_DATE DATE,
		constraint ATGTR_SHOW_PK primary key(SHOW_ID)
	);
	
create table ATGTR_SHOW_PRIZE(
		SHOW_ID VARCHAR2(40) NOT NULL,
		SEQ_NUM NUMBER NOT NULL,
		PRIZE_ID VARCHAR2(40),
		constraint ATGTR_SHOW_PRIZE_PK primary key (SHOW_ID, SEQ_NUM)
	);
	
create table ATGTR_CAT_SHOW(
		SHOW_ID VARCHAR2(40) NOT NULL,
		CAT_ID VARCHAR2(40) NOT NULL,
		SEQ_NUM NUMBER NOT NULL,
		constraint ATGTR_CAT_SHOW_PK primary key(CAT_ID, SHOW_ID, SEQ_NUM)
);